Nzen/Models/Analysis.cs
namespace Nzen.Models
{
    #region using
    using CotohaAPI.Models;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using TextAnalysisServiceAPI.Models;
    #endregion

    /// <summary>
    /// 
    /// </summary>
    public class AnalysisModel
    {

        public KeyPhraseExtractResponce KeyPhraseExtractResult { get; set; } = new KeyPhraseExtractResponce();

        /// <summary>
        /// 
        /// </summary>
        public KeyWordResponce KeywordResult { get; set; } = new KeyWordResponce();

        /// <summary>
        /// 
        /// </summary>
        public SentimentResponce SentimentResult { get; set; } = new SentimentResponce();

        /// <summary>
        /// 
        /// </summary>
        public TargetEventInfo Info { get; set; } = new TargetEventInfo();

        public PresenterInfo Presenter { get; set; } = new PresenterInfo();
    }

    /// <summary>
    /// 
    /// </summary>
    public class TargetEventInfo
    {
        public string GroupId { get; set; }

        public DateTime EventDate { get; set; }

    }

    /// <summary>
    /// 
    /// </summary>
    public class PresenterInfo
    {
        public List<string> SpeachText { get; set; } = new List<string>();

    }

    /// <summary>
    /// 
    /// </summary>
    public class AudienceInfo
    {
        public List<string> Comments { get; set; } = new List<string>();

    }
}

Nzen/Models/ErrorViewModel.cs
namespace Nzen.Models
{
    using System;

    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Nzen/Models/EventDataModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nzen.Models
{
    public class EventDataModel
    {
        public int serial_no { get; set; }

        public string group_id { get; set; }

        public string group_entry_date { get; set; }

        public string info_type { get; set; }

        public string data { get; set; }
    }
}

Nzen/Models/HomeModel.cs
namespace Nzen.Models
{
    #region using
    using Nzen.Manager;
    #endregion

    public class HomeModel
    {
        public string UserName { get; set; } = string.Empty;

        public string GroupId { get; set; } = string.Empty;

        public string Content { get; set; } = string.Empty;

        public ApplicationEnv Env { get; set; }
    }
}

Nzen/Controllers/AnalysisController.cs
namespace Nzen.Controllers
{
    #region using

    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Diagnostics;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    using Nzen.Manager;
    using Nzen.Models;
    using CotohaAPI;
    using TextAnalysisServiceAPI;

    #endregion


    /// <summary>
    /// 
    /// </summary>
    public class AnalysisController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            return View("Index");
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="info"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> ResultData(TargetEventInfo info)
        {
            var rawDataList = DatabaseManager.Executor.GetEventData(info.GroupId, info.EventDate);

            if (rawDataList.Count() == 0) return View("Index");


            AnalysisModel model = new AnalysisModel();
            model.Presenter.SpeachText = rawDataList.Where(data => data.info_type == "presentor")
                                                    .OrderBy(data => data.serial_no)
                                                    .Select((data) => data.data)
                                                    .ToList();


            await ExecuteAnalysis(model);

            return View("Result", model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        private async Task ExecuteAnalysis(AnalysisModel model)
        {
            var tokenResult = await CotohaApiManager.GetAccessTokenAsync();

            if (tokenResult.StatusCode == HttpStatusCode.Created)
            {
                model.KeywordResult = await CotohaApiManager.ExtractionKeywordsAsync(new CotohaAPI.Models.KeyWordRequest()
                {
                    Document = model.Presenter.SpeachText,
                    Type = "kuzure",
                    DoSegment = true,
                    MaxKeywordNum = 10
                });

                model.KeyPhraseExtractResult = 
                    await TextAnalyticsManager.ExecuteJapaneseKeyPhraseExtractAsync(string.Join("。", model.Presenter.SpeachText));
            }
        }
    }
}

Nzen/Controllers/HomeController.cs
namespace Nzen.Controllers
{
    #region using
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Diagnostics;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Nzen.Manager;
    using Nzen.Models;
    #endregion

    public class HomeController : Controller
    {
        private ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        #region Common

        [HttpGet]
        public IActionResult Index()
        {
            return View(new HomeModel());
        }

        [HttpGet]
        public IActionResult Invite(string groupId)
        {
            return View("Index",new HomeModel() { GroupId= groupId});
        }

        #endregion

        #region user

        [HttpPost]
        public IActionResult ChatRoom(HomeModel model)
        {
            ViewData["Message"] = "ChatRoom.";
            return View(model);
        }
        #endregion

        #region presenter

        [HttpPost]
        public IActionResult PresenterPrepare(HomeModel model)
        {
            if (string.IsNullOrEmpty(model.GroupId))
            {
                model.GroupId = GroupIdManager.Instance.GetGroupId(model.UserName);
            }
            else
            {
                if (GroupIdManager.Instance.IsExistGroupId(model.GroupId) == false)
                {
                    StringBuilder sb = new StringBuilder();
                    sb.AppendLine("指定されたグループIDは存在しません。\r\n");
                    sb.AppendLine("新しいグループIDを作成する場合は、\r\n");
                    sb.AppendLine("グループIDを空白にしたままJoinしてください。");
                    this.ViewData["ErrorMessage"] = sb.ToString();
                    return View("Index", new HomeModel());
                }
            }
            ModelState.Clear();

            ViewData["GroupId"] = model.GroupId;
            return View(model);
        }

        [HttpPost]
        public IActionResult PresentationRoom(HomeModel model)
        {
            model.Env = ApplicationEnv.Env;
            return View(model);
        }

        #endregion

        #region system error

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var error = HttpContext.Features.Get<IExceptionHandlerFeature>();
            _logger.LogError(error?.Error, $"{HttpContext.User.Identity.Name}が{DateTime.Now.ToString()}にエラーを発生させたよ！");

            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        #endregion
    }
}

Nzen/Controllers/PresentationDataController.cs
namespace Nzen.Controllers
{
    #region using
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Nzen.Manager;
    #endregion


    [Route("api/[controller]")]
    [ApiController]
    public class PresentationDataController : ControllerBase
    {

        //https://localhost:44362/api/PresentationData?groupId=54OJ&date=2019-06-17
        [HttpGet]
        public JsonResult GetPresentationText(string date, string groupId)
        {
            System.Text.RegularExpressions.Regex.IsMatch(date, "^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}$");


            return new JsonResult(DatabaseManager.Executor.GetPresentationText(groupId, DateTime.Parse(date)));
        }
    }
}

Nzen/Views/Analysis/Index.cshtml
@model AnalysisModel

    <form id="show_result" asp-controller="Analysis" asp-action="ResultData" method="post">

        <div class="wrapper">
            <div class="page-header page-header-small">
                <div class="page-header-image" data-parallax="true" style="background-image: url('/images/analysis.jpg');">
                </div>
                <div class="content-center">
                    <div class="container">
                        <h1 class="title">Analysis</h1>
                    </div>
                </div>
            </div>
            <div class="section section-team text-center">
                <div class="container">
                    <div class="input-group  input-lg">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="now-ui-icons users_circle-08"></i>
                            </span>
                        </div>
                        @Html.TextBoxFor(model => model.Info.GroupId, new { @class = "form-control", @id = "inputUserName", @placeholder = "groupID" })
                    </div>

                    <div class="input-group  input-lg">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="now-ui-icons ui-1_calendar-60"></i>
                            </span>
                        </div>
                        @Html.TextBoxFor(model => model.Info.EventDate, new { @id="eventDate",@class = "form-control date-picker ", @placeholder = "mm/dd/yyyy" })
                    </div>
                </div>
                <input id="showResultButton" type="submit" class="btn btn-primary btn-round" value="Show Result" form="show_result" />
            </div>
        </div>
    </form>

Nzen/Views/Analysis/Result.cshtml
@model AnalysisModel
<style>
    .result-container {
        height: 340Px;
        margin-bottom: 20px;
    }
</style>


<form id="show_result" asp-controller="Analysis" asp-action="ResultData" method="post">

    <div class="wrapper">
        @*ページヘッダー*@
        <div class="page-header page-header-small">
            <div class="page-header-image" data-parallax="true" style="background-image: url('/images/analysis_result.jpg')">
            </div>
            <div class="content-center">
                <div class="container">
                    <h1 class="title">Analysis Result</h1>
                </div>
            </div>
        </div>

        @*結果コンテンツ*@
        <div class="result-container">
            <div class=" w-50 float-left h-100">
                <div class="text-center">
                    <img class="  media-middle" src="~/images/summary.jpg" />
                </div>
            </div>
            <div class="w-50 float-right h-100 ">
                <div class="card text-center">
                    <div class="card-body text-left pre-scrollable">
                        <h4 class="card-title">基本情報</h4>

                        <p class="card-text">@Model.Info.EventDate</p>
                        <p class="card-text">@Model.Info.GroupId</p>
                        <p class="card-text">その他情報（発表時間、参加者人数、コメント数、）</p>
                        <p class="card-text">その他情報（発表時間、参加者人数、コメント数、）</p>
                        <p class="card-text">その他情報（発表時間、参加者人数、コメント数、）</p>
                        <p class="card-text">その他情報（発表時間、参加者人数、コメント数、）</p>
                        <p class="card-text">その他情報（発表時間、参加者人数、コメント数、）</p>
                        <p class="card-text">その他情報（発表時間、参加者人数、コメント数、）</p>
                        <p class="card-text">その他情報（発表時間、参加者人数、コメント数、）</p>
                        <p class="card-text">その他情報（発表時間、参加者人数、コメント数、）</p>
                        <p class="card-text">その他情報（発表時間、参加者人数、コメント数、）</p>
                        <p class="card-text">その他情報（発表時間、参加者人数、コメント数、）</p>
                        <p class="card-text">その他情報（発表時間、参加者人数、コメント数、）</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="result-container">

            <div class=" w-50 float-left h-100">
                <div class="card text-center">
                    <div class="card-body  text-left pre-scrollable">
                        <h4 class="card-title">発表のキーワード</h4>
                        <ul>
                            @foreach (var docs in Model.KeyPhraseExtractResult.Documents)
                            {
                                foreach (var keyphrases in docs.KeyPhrases)
                                {
                                    <li class="card-text">@keyphrases</li>
                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div class="w-50 float-right h-100 ">
                <div class="text-center media-middle">
                    <img class="text-center" src="~/images/keyword_header.jpg" />
                </div>
            </div>

        </div>

        <div class="result-container">
            <div class=" w-50 float-left h-100  ">
                <div class="text-center media-middle">
                    <img class="card-img-top text-center" src="~/images/speach_text.jpg">
                </div>
            </div>
            <div class="card w-50 float-right h-100">
                <div class="card-body text-left pre-scrollable">
                    <h4 class="card-title">発表内容(Speach to Text)</h4>
                    @foreach (var doc in Model.Presenter.SpeachText)
                    {
                        <p class="card-text">@doc</p>
                    }
                </div>
            </div>
        </div>

        <div class="result-container">
            <div class="card ">
                <div class="card-body text-left  pre-scrollable" >
                    <h4 class="card-title">参加者からのコメント(Speach to Text)</h4>
                    @foreach (var doc in Model.Presenter.SpeachText)
                    {
                        <p class="card-text">

                            時間：コメント みたいにする
                        </p>
                    }

                </div>
            </div>

        </div>
    </div>
</form>

Nzen/Views/Home/ChatRoom.cshtml
@model HomeModel
@{
    Layout = "~/Views/Shared/_Layout_chat.cshtml";
}

<link href="~/css/Contact.css" rel="stylesheet" />

<main role="main" class="container">
    <div id="frame">
        <div class="content">
            <div class="contact-profile" style="color:white">
                User ID：
                <btn class="btn btn-info btn-sm">@Model.UserName</btn>
                イベントグループID：
                <btn class="btn btn-info btn-sm">@Model.GroupId</btn>
                にログイン中！
            </div>

            <div class="messages">
                <ul id="messagesList" style="padding-left: 0px !important"></ul>
            </div>
            <div class="message-input">
                <div class="wrap">
                    <input type="text" id="messageInput" placeholder="Write your message..." />
                    <button id="sendButton" type="submit">
                        <i class="fa fa-paper-plane" aria-hidden="true"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</main>

<div hidden>
    @Html.TextBoxFor(model => model.UserName, new { @id = "userName" })
    @Html.TextBoxFor(model => model.GroupId, new { @id = "groupId" })
</div>

<script src="~/lib/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>

<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script>
<script src='https://code.jquery.com/jquery-2.2.4.min.js'></script>
<script>
    $(".messages").animate({ scrollTop: $(document).height() }, "fast");

    $("#profile-img").click(function () {
        $("#status-options").toggleClass("active");
    });

    $(".expand-button").click(function () {
        $("#profile").toggleClass("expanded");
        $("#contacts").toggleClass("expanded");
    });

    $("#status-options ul li").click(function () {
        $("#profile-img").removeClass();
        $("#status-online").removeClass("active");
        $("#status-away").removeClass("active");
        $("#status-busy").removeClass("active");
        $("#status-offline").removeClass("active");
        $(this).addClass("active");

        if ($("#status-online").hasClass("active")) {
            $("#profile-img").addClass("online");
        } else if ($("#status-away").hasClass("active")) {
            $("#profile-img").addClass("away");
        } else if ($("#status-busy").hasClass("active")) {
            $("#profile-img").addClass("busy");
        } else if ($("#status-offline").hasClass("active")) {
            $("#profile-img").addClass("offline");
        } else {
            $("#profile-img").removeClass();
        };
        $("#status-options").removeClass("active");
    });
</script>

Nzen/Views/Home/Contact.cshtml
@model HomeModel


<link href="~/css/Contact.css" rel="stylesheet" />

<main role="main" class="container">
    <div id="frame">
        <div class="content">
            <div class="contact-profile">
                <p>User ID : @Model.UserName , Room ID : @Model.GroupId</p>
            </div>
            <div class="messages">
                <ul id="messagesList" style="padding-left: 0px !important">
                </ul>
            </div>
            <div class="message-input">
                <div class="wrap">
                    <input type="text" id="messageInput" placeholder="Write your message..." />
                    <button id="sendButton" type="submit">
                        <i class="fa fa-paper-plane" aria-hidden="true"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</main>

<div hidden>
    @Html.TextBoxFor(model => model.UserName, new { @id = "userName" })
    @Html.TextBoxFor(model => model.GroupId, new { @id = "groupId" })
</div>
<script src="~/lib/signalr/dist/browser/signalr.js"></script>
<script src="~/js/chat.js"></script>

<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script>
<script src='https://code.jquery.com/jquery-2.2.4.min.js'></script>
<script>
    $(".messages").animate({ scrollTop: $(document).height() }, "fast");

    $("#profile-img").click(function () {
        $("#status-options").toggleClass("active");
    });

    $(".expand-button").click(function () {
        $("#profile").toggleClass("expanded");
        $("#contacts").toggleClass("expanded");
    });

    $("#status-options ul li").click(function () {
        $("#profile-img").removeClass();
        $("#status-online").removeClass("active");
        $("#status-away").removeClass("active");
        $("#status-busy").removeClass("active");
        $("#status-offline").removeClass("active");
        $(this).addClass("active");

        if ($("#status-online").hasClass("active")) {
            $("#profile-img").addClass("online");
        } else if ($("#status-away").hasClass("active")) {
            $("#profile-img").addClass("away");
        } else if ($("#status-busy").hasClass("active")) {
            $("#profile-img").addClass("busy");
        } else if ($("#status-offline").hasClass("active")) {
            $("#profile-img").addClass("offline");
        } else {
            $("#profile-img").removeClass();
        };

        $("#status-options").removeClass("active");
    });
</script>

Nzen/Views/Home/Index.cshtml
@model HomeModel
@{
    ViewData["Title"] = "Home Page";
    //Layout = "~/Views/Shared/_Layout_signin.cshtml";
}
<script type="text/javascript" src="~/js/Index.js"></script>


<!-- Navbar -->
<div class="login-page">
    <div class="page-header clear-filter" filter-color="orange">
        <div class="page-header-image" style="background-image:url(/images/login_back.jpg)"></div>
        <!-- End Navbar -->

        <div class="container">
            <div class="content">
                <div id="messageBox" class="alert alert-danger" role="alert" hidden>
                    <div class="container">
                        <strong>Error!</strong>
                        <label id="errorLavel">@ViewData["ErrorMessage"]</label>
                        <!-- TODO：いつか復活させるかも
                        <button id="alartCloseButton" type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">
                                <i class="now-ui-icons ui-1_simple-remove"></i>
                            </span>
                        </button>
                        -->
                    </div>
                </div>
                <div class="col-md-4 ml-auto mr-auto">

                    <form id="forpresenter" class="form" asp-controller="Home" asp-action="PresenterPrepare" hidden>
                        @Html.TextBoxFor(model => model.UserName, new { @id = "inputUserName2" })
                        @Html.TextBoxFor(model => model.GroupId, new { @id = "inputGroupId2" })
                    </form>

                    <form id="foruser" class="form" asp-controller="Home" asp-action="ChatRoom">
                        <div class="card card-login card-plain">
                            <div class="card-header text-center">
                                <div class="logo-container">
                                    <img src="~/images/N.png" alt="">
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="input-group no-border input-lg">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="now-ui-icons users_circle-08"></i>
                                        </span>
                                    </div>
                                    @Html.TextBoxFor(model => model.UserName, new { @class = "form-control", @id = "inputUserName", @placeholder = "name" })
                                </div>
                                <div class="input-group no-border input-lg">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="now-ui-icons text_caps-small"></i>
                                        </span>
                                    </div>
                                    @Html.TextBoxFor(model => model.GroupId, new { @class = "form-control", @id = "inputGroupId", @placeholder = "groupID" })
                                </div>
                            </div>
                            <div class="card-footer text-center">
                                <button id="joinAudienceButton" class="btn btn-primary btn-round btn-lg btn-block" type="submit" form="foruser">Join as an audience</button>
                            </div>
                            <div class="card-footer text-center">
                                <button id="joinPresenterButton" class="btn btn-secondary btn-round btn-lg btn-block" type="submit" form="forpresenter">Join as a presenter</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

Nzen/Views/Home/PresentationRoom.cshtml
@model HomeModel
@{
    Layout = "~/Views/Shared/_Layout_presentor.cshtml";
}

<div name="main_contents">

    @*Screen*@
    <div id="nicoscreen" class="overpanel slideshare">
        @if (String.IsNullOrWhiteSpace(Model.Content) == true)
        {
            <iframe id="nicoframe" src="//www.slideshare.net/slideshow/embed_code/key/u6WNbsR5worSzC" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen></iframe>
            <div style="margin-bottom:5px">
                <strong>
                    <a href="//www.slideshare.net/EdurekaIN/what-is-artificial-intelligence-artificial-intelligence-tutorial-for-beginners-edureka" title="What is Artificial Intelligence | Artificial Intelligence Tutorial For Beginners | Edureka" target="_blank">What is Artificial Intelligence | Artificial Intelligence Tutorial For Beginners | Edureka</a>
                </strong> from <strong>
                    <a href="https://www.slideshare.net/EdurekaIN" target="_blank">
                        Edureka!
                    </a>
                </strong>
            </div>
        }
        else
        {
            @Html.Raw(Model.Content)
        }

    </div>


    @*音声解析*@
    <div id="phraseDiv" class="text-primary text-primary" style="font-size:25px">
    </div>
</div>


<div hidden>
    @Html.TextBoxFor(model => model.UserName, new { @id = "userName" })
    @Html.TextBoxFor(model => model.GroupId, new { @id = "groupId" })
    @Html.TextBoxFor(model => model.Env.SpeechAPI_Region, new { @id = "regionKey" })
    @Html.TextBoxFor(model => model.Env.SpeechAPI_Key, new { @id = "subscriptionKey" })
</div>

<script src="~/js/NicoScreen.js"></script>
<script src="~/lib/SpeechSDK-JavaScript-1.4.1/microsoft.cognitiveservices.speech.sdk.bundle.js"></script>
<script src="~/js/SpeechSDKImpl.js"></script>

<script type="text/javascript">
    var obj = {
        //基本情報が設定できます
        "base": {
            color: "White", //文字の色を指定します
            speed: "normal", //文字が流れるスピードを指定します。slow/fast/normal
            interval: "normal",//文字が流れる間隔を指定します。slow/fast/normal
            font_size: "30px", //フォントのサイズを指定します。
            loop: false //文字が最後まで流れた後に、繰り返すかどうか　true/false
        },

        "comments": [
            "", //Error防止用
        ]
    };
    nicoscreen.set(obj);
    nicoscreen.start();
</script>

Nzen/Views/Home/PresenterContact.cshtml
@model HomeModel
@{
    Layout = "~/Views/Shared/_Layout_presentor.cshtml";
}

<div id="nicoscreen" class="overpanel slideshare">
    @if (String.IsNullOrWhiteSpace(Model.Content) == true)
    {
        <iframe id="nicoframe" src="//www.slideshare.net/slideshow/embed_code/key/u6WNbsR5worSzC" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen></iframe>
        <div style="margin-bottom:5px">
            <strong>
                <a href="//www.slideshare.net/EdurekaIN/what-is-artificial-intelligence-artificial-intelligence-tutorial-for-beginners-edureka" title="What is Artificial Intelligence | Artificial Intelligence Tutorial For Beginners | Edureka" target="_blank">What is Artificial Intelligence | Artificial Intelligence Tutorial For Beginners | Edureka</a>
            </strong> from <strong>
                <a href="https://www.slideshare.net/EdurekaIN" target="_blank">
                    Edureka!
                </a>
            </strong>
        </div>
    }
    else
    {
        @Html.Raw(Model.Content)
    }

</div>
<div id="phraseDiv" class="blockquote blockquote-primary " style="height:10%">
</div>


<div hidden>
    @Html.TextBoxFor(model => model.UserName, new { @id = "userName" })
    @Html.TextBoxFor(model => model.GroupId, new { @id = "groupId" })
    @Html.TextBoxFor(model => model.Env.SpeechAPI_Region, new { @id = "regionKey" })
    @Html.TextBoxFor(model => model.Env.SpeechAPI_Key, new { @id = "subscriptionKey" })
</div>

<script src="~/js/NicoScreen.js"></script>
<script src="~/lib/SpeechSDK-JavaScript-1.4.1/microsoft.cognitiveservices.speech.sdk.bundle.js"></script>
<script src="~/js/SpeechSDKImpl.js"></script>

<script type="text/javascript">
    var obj = {
        //基本情報が設定できます
        "base": {
            color: "White", //文字の色を指定します
            speed: "normal", //文字が流れるスピードを指定します。slow/fast/normal
            interval: "normal",//文字が流れる間隔を指定します。slow/fast/normal
            font_size: "30px", //フォントのサイズを指定します。
            loop: false //文字が最後まで流れた後に、繰り返すかどうか　true/false
        },

        "comments": [
            "", //Error防止用
        ]
    };
    nicoscreen.set(obj);
    nicoscreen.start();
</script>

Nzen/Views/Home/PresenterPrepare.cshtml
@model HomeModel

<form method="post" asp-action="PresentationRoom" asp-controller="Home">
    <div class="wrapper">
        <div class="page-header page-header-small">
            <div class="page-header-image" data-parallax="true" style="background-image: url('/images/meeting_back.jpg');">
            </div>
            <div class="content-center">
                <div class="container">
                    <h1 class="title">waiting room</h1>
                    <div class="text-center">
                            <a href="https://www.slideshare.net/" class="btn btn-primary btn-icon btn-round"  target="_blank"  rel="SlidShare">
                                <i class="fab">
                                    <img src="~/images/slideshare-icon.svg" />
                                </i>
                            </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="section section-team text-center">
            <div class="container">
                <div class="team">
                    <div class="row">
                        <label for="comment">
                            your group ID is
                            <strong>@Model.GroupId</strong>
                        </label>
                    </div>

                    <div class="row">
                        <label for="comment">embeded iflame:</label>
                        @Html.TextAreaFor(model => model.Content, new { @class = "form-control", @id = "comment", @row = 5, @placeholder = "ここにSlideshareのEmbedリンクを貼り付けて下さい" })
                        <button class="btn btn-primary btn-round" type="submit">
                            Start Presentation
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div hidden>
        @Html.TextBoxFor(model => model.GroupId, new { @id = "groupId" })
        @Html.TextBoxFor(model => model.UserName, new { @id = "userName" })
    </div>
</form>